version: "3.7"
services:

  servers:
    build: ./servers
    image: danijelradakovic/servers:1.1.0
    container_name: servers
    restart: on-failure
    networks:
      - demo-tls
    ports:
      - 8080:8080
    environment:
      DATABASE_USERNAME: sa
      DATABASE_PASSWORD: zgadija
      DATABASE_DOMAIN: mysql
      DATABASE_SCHEMA: servers
      KEYSTORE: /etc/keystore/SERVERS_NAME.keystore.p12
      KEYSTORE_PASSWORD: SERVERS_KEYSTORE_PASSWORD
      KEYSTORE_ALIAS: SERVERS_ALIAS
      TRUSTSTORE: /etc/keystore/SERVERS_NAME.truststore.p12
      TRUSTSTORE_PASSWORD: SERVERS_KEYSTORE_PASSWORD
      RMQ_HOST: rabbitmq-broker
      RMQ_PORT: 5671
    volumes:
      - ./tls/certs/SERVERS_NAME/keystore:/etc/keystore
    depends_on: 
      - mysql
      - rabbitmq-broker

  report:
    build: ./Servers-Report
    image: danijelradakovic/report:1.1.0
    container_name: report
    restart: on-failure
    networks:
      - demo-tls
    ports:
      - 8081:8080
    environment:
      DOMAIN: servers
      PORT: 8080
      KEYSTORE: /etc/keystore/REPORT_NAME.keystore.p12
      KEYSTORE_PASSWORD: REPORT_KEYSTORE_PASSWORD
      KEYSTORE_ALIAS: REPORT_ALIAS
      TRUSTSTORE: /etc/keystore/REPORT_NAME.truststore.p12
      TRUSTSTORE_PASSWORD: REPORT_KEYSTORE_PASSWORD
      RMQ_HOST: rabbitmq-broker
      RMQ_PORT: 5671
    volumes:
      - ./tls/certs/REPORT_NAME/keystore:/etc/keystore
    depends_on:
      - rabbitmq-broker

  logan:
    build: ./Log-Analyzer
    image: danijelradakovic/logan:1.1.0
    container_name: logan
    restart: on-failure
    networks:
      - demo-tls
    ports:
      - 8082:8080
    environment:
      LOG_STORAGE: /var/log/web-traffic.log
      KEYSTORE: /etc/keystore/LOGAN_NAME.keystore.p12
      KEYSTORE_PASSWORD: LOGAN_KEYSTORE_PASSWORD
      KEYSTORE_ALIAS: LOGAN_ALIAS
      TRUSTSTORE: /etc/keystore/LOGAN_NAME.truststore.p12
      TRUSTSTORE_PASSWORD: LOGAN_KEYSTORE_PASSWORD
      RMQ_HOST: rabbitmq-broker
      RMQ_PORT: 5671
    volumes:
      - logs:/var/log
      - ./tls/certs/LOGAN_NAME/keystore:/etc/keystore
    depends_on:
      - rabbitmq-broker

  mysql:
    image: mysql:8.0.19
    container_name: mysql
    restart: always
    networks:
      - demo-tls
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: sa
      MYSQL_PASSWORD: zgadija
      MYSQL_DATABASE: servers
    volumes:
      - mysql-data:/var/lib/mysql

  rabbitmq-broker:
    image: rabbitmq:management-alpine
    container_name: rabbitmq-broker
    ports:
      - 5672:5672
      - 5671:5671
      - 15671:15671
    networks:
      - demo-tls
    environment:
      RABBITMQ_SSL_CACERTFILE: /etc/rabbitmq/cert/tls-ca-chain.pem
      RABBITMQ_SSL_CERTFILE: /etc/rabbitmq/cert/RMQ_NAME.crt
      RABBITMQ_SSL_FAIL_IF_NO_PEER_CERT: "true"
      RABBITMQ_SSL_KEYFILE: /etc/rabbitmq/cert/RMQ_NAME.key
      RABBITMQ_SSL_VERIFY: verify_peer
    volumes:
      - ./tls/certs/RMQ_NAME:/etc/rabbitmq/cert

volumes:
  mysql-data:
  logs:

networks:
  demo-tls:
    name: demo-tls
    driver: bridge
