version: "3.8"
services:

  servers:
    image: danijelradakovic/servers:1.0.0
    networks:
      - demo
    ports:
      - 8080:8080
    environment:
      DATABASE_USERNAME: sa
      DATABASE_PASSWORD: zgadija
      DATABASE_DOMAIN: mysql
      DATABASE_SCHEMA: servers
      RMQ_HOST: rabbitmq-broker
    depends_on:
      - mysql
      - rabbitmq-broker
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

  logan:
    image: danijelradakovic/logan:1.0.0
    networks:
      - demo
    ports:
      - 8081:8080
    environment:
      LOG_STORAGE: /var/log/web-traffic.log
      RMQ_HOST: rabbitmq-broker
    volumes:
      - logs:/var/log
    depends_on:
      - rabbitmq-broker
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  mysql:
    image: mysql:8.0.19
    networks:
      - demo
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: sa
      MYSQL_PASSWORD: zgadija
      MYSQL_DATABASE: servers
    volumes:
      - mysql-data:/var/lib/mysql
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

  rabbitmq-broker:
    image: rabbitmq:management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - demo
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

volumes:
  mysql-data:
  logs:

networks:
  demo:
    name: demo
