version: "3.7"
services:

  servers:
    image: danijelradakovic/servers:1.0.0
    container_name: servers
    restart: on-failure
    networks:
      - demo
    ports:
      - 8080:8080
    environment:
      DATABASE_USERNAME: sa
      DATABASE_PASSWORD: zgadija
      DATABASE_DOMAIN: mysql
      DATABASE_SCHEMA: servers
      RMQ_HOST: rabbitmq-broker
    depends_on: 
      - mysql
      - rabbitmq-broker

  logan:
    image: danijelradakovic/logan:1.0.0
    container_name: logan
    restart: on-failure
    networks:
      - demo
    ports:
      - 8081:8080
    environment:
      LOG_STORAGE: /var/log/web-traffic.log
      RMQ_HOST: rabbitmq-broker
    volumes:
      - logs:/var/log
    depends_on:
      - rabbitmq-broker

  mysql:
    image: mysql:8.0.19
    container_name: mysql
    restart: always
    networks:
      - demo
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: sa
      MYSQL_PASSWORD: zgadija
      MYSQL_DATABASE: servers
    volumes:
      - mysql-data:/var/lib/mysql

  rabbitmq-broker:
    image: rabbitmq:management-alpine
    container_name: rabbitmq-broker
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - demo

volumes:
  mysql-data:
  logs:

networks:
  demo:
    name: demo
    driver: bridge
